// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpCKq0CP4QmqZeQogdR9ATTjQ2MTE31S0',
    appId: '1:1014051549145:web:5045a56a7f0f23f54273c8',
    messagingSenderId: '1014051549145',
    projectId: 'musicfinder-1e651',
    authDomain: 'musicfinder-1e651.firebaseapp.com',
    storageBucket: 'musicfinder-1e651.firebasestorage.app',
    measurementId: 'G-53YZ2VQTVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfMjdPXwQJAqMd8Y8XDt30nAkiW1CjvW4',
    appId: '1:1014051549145:android:e1b26b02820a0c614273c8',
    messagingSenderId: '1014051549145',
    projectId: 'musicfinder-1e651',
    storageBucket: 'musicfinder-1e651.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWqtq8zYrbFqADpdDtXXgs-HeIpYHp-jc',
    appId: '1:1014051549145:ios:d5ffa6540d7e55384273c8',
    messagingSenderId: '1014051549145',
    projectId: 'musicfinder-1e651',
    storageBucket: 'musicfinder-1e651.firebasestorage.app',
    iosBundleId: 'com.antigravity.egyptmusic.egyptMusicCommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWqtq8zYrbFqADpdDtXXgs-HeIpYHp-jc',
    appId: '1:1014051549145:ios:d5ffa6540d7e55384273c8',
    messagingSenderId: '1014051549145',
    projectId: 'musicfinder-1e651',
    storageBucket: 'musicfinder-1e651.firebasestorage.app',
    iosBundleId: 'com.antigravity.egyptmusic.egyptMusicCommunity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpCKq0CP4QmqZeQogdR9ATTjQ2MTE31S0',
    appId: '1:1014051549145:web:1a37f17af79159e34273c8',
    messagingSenderId: '1014051549145',
    projectId: 'musicfinder-1e651',
    authDomain: 'musicfinder-1e651.firebaseapp.com',
    storageBucket: 'musicfinder-1e651.firebasestorage.app',
    measurementId: 'G-2WHEGZDC7G',
  );
}
